### ISSUE TITLE
Integrating heuristic-based optimisation option 

### ISSUE THREAD

**Issue by mducroux** [nchain-innovation/chain-gang#12]
Would it be possible to integrate an optimisation option in the Script class, so that when this option is enabled, the script that is returned to the user is optimised according to some heuristic rules, like: if there is "OP_TOALTSTACK OP_FROMALTSTACK" or "OP_FROMALTSTACK OP_TOALTSTACK" in the script (which are useless), they are removed. This would be helpful for anyone constructing complex script, where this might reduce the script size significantly.

**Comment by arthurggordon** [comment]
This sounds like something that would be easier to build/prototype using the Python `tx-engine`.
Ideally there would be a language for the heuristics (perhaps a subset of Python), to enable new heuristics/rulesets to be added to the system.

**Comment by mducroux** [comment]
May be implemented once we have a stronger need and the rule set becomes bigger
