### ISSUE TITLE
Please add Wallet functionality for int/hex

### ISSUE THREAD

**Issue by j-wilden** [nchain-innovation/chain-gang#18]
Please can you add the following: 

**Create key from hex and from int:**

```
myPrivKey = PrivateKey.from_hex( <hex-format-pkey> , network="BSV_testnet")
myPrivKey = PrivateKey.from_int( <int-format-pkey> , network="BSV_testnet")
```

**Return hex and int from Wallet**

```
myPrivKey = Wallet( <wif-format-pkey> ) 
myPrivKey.to_hex())
myPrivKey.to_int())
```

**Test Unit**

Tests have been added to `test_wallet.py` on the wallet_functions branch

**Comment by murphyj8** [comment]
Completed and released in v0.6.7
