### ISSUE TITLE
OP_BIN2NUM implementation

### ISSUE THREAD

**Issue by BarbacoviF** [nchain-innovation/chain-gang#2]
The current implementation of `OP_BIN2NUM `doesn't reflect the node software implementation. 

In the BSV software `OP_BIN2NUM` pops the element from the stack and minimally encodes it (namely, it pops a byte sequence and interprets it as a number, but it doesn't reverse its endianness): [OP_BIN2NUM in BSV node software](https://github.com/bitcoin-sv/bitcoin-sv/blob/master/src/script/interpreter.cpp#L1622).

In chain-gang, `OP_BIN2NUM` reverses the endianness: [OP_BIN2NUM in chain-gang](https://github.com/nchain-innovation/chain-gang/blob/main/src/script/interpreter.rs#L587).
 
The following code should return `True`, but it returns `False`:

```python
from tx_engine import Script, Context

test = Script.parse_string('0x0100 OP_BIN2NUM OP_1 OP_EQUAL')
context = Context(script=test)
context.evaluate()
```

**Comment by arthurggordon** [comment]
Should be addressed in version 0.5.9 See https://github.com/nchain-innovation/chain-gang/compare/db61f25b1d6a05eab73ca54685895c972baba5fc...bdebcff43f73d2cba5f3152cb44034fb8ef19dcf
